### ISSUE TITLE
Use GitHub Actions concurrency

### ISSUE THREAD

**Issue by rahulporuri** [enthought/ets#71]
At the moment, pushing commits to a PR where GitHub Actions CI is alreaady running does not cancel the running job. Instead, the job continues running and a new job is scheduled. This is unnecessarily wasteful and adds delays to the time CI takes on our PRs.

It looks like GitHub Actions concurrency is the answer to this problem. We need to include the following in our jobs - 

```
concurrency: 
  # These lines should have the effect of cancelling CI runs for
  # existing commits when a new commit is pushed to the PR.
  group: ${{ github.head_ref }}
  cancel-in-progress: true
```

- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
